blueprint:
  name: Motion Light Standard
  description: >
    Turn on lights (and optional switches) when motion is detected.
    Turn off after a configurable no-motion delay. Supports both lights
    and switches (e.g. mirror cabinet, fan).
  domain: automation
  input:
    motion_sensor:
      name: Bewegungsmelder
      description: Binärer Sensor der Bewegung erkennt.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Licht(er)
      description: Welche Lichter gesteuert werden sollen.
      default: {}
      selector:
        target:
          entity:
            domain: light
    switch_target:
      name: Switch(es) — optional
      description: >
        Zusätzliche Switches die zusammen mit den Lichtern gesteuert werden
        (z.B. Spiegelschrank, Ventilator).
      default: {}
      selector:
        target:
          entity:
            domain: switch
    no_motion_wait:
      name: Wartezeit nach letzter Bewegung
      description: Wie lange nach der letzten Bewegung Licht und Switches noch an bleiben.
      default:
        hours: 0
        minutes: 30
        seconds: 0
      selector:
        duration: {}
    transition_on:
      name: Einblend-Zeit (Sekunden)
      description: Wie lange das Licht zum Einblenden braucht.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: s
    transition_off:
      name: Ausblend-Zeit (Sekunden)
      description: Wie lange das Licht zum Ausblenden braucht.
      default: 10
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: s

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"

action:
  - service: light.turn_on
    target: !input light_target
    data:
      transition: !input transition_on
  - service: switch.turn_on
    target: !input switch_target
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        to: "off"
        for: !input no_motion_wait
    timeout:
      hours: 2
    continue_on_timeout: true
  - service: light.turn_off
    target: !input light_target
    data:
      transition: !input transition_off
  - service: switch.turn_off
    target: !input switch_target

mode: restart
